language: python
os: linux
dist: focal
python:
  - "3.8"
services:
  - docker
  # - mysql
before_install:
  - docker-compose up

  # - docker run messmanagamentsystem:latest /bin/sh -c "pytest"
install:
  - pip install -r requirements.txt
before_script:
  - export FLASK_APP=runserver.py
  # - mysql -e 'CREATE DATABASE mydatabase;'
script:
  # - flask db init
  # - flask db migrate -m "Initial Migration" 
#  - pytest --cov=Mess_Management_System tests/
notifications:
  on_success: always
  on_failure: always
