language: python
os: linux
dist: focal
python:
  - "3.8"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - docker-compose up --build
notifications:
  on_success: always
  on_failure: always
