language: python
os: linux
dist: focal
python:
  - "3.8"
services:
  - docker
before_install:
  - docker build -t messmanagamentsystem:latest .
  - docker ps -a
  # - docker run messmanagamentsystem:latest /bin/sh -c "pytest"
install:
  - pip install -r requirements.txt
before_script:
  - export FLASK_APP=runserver.py
  - export DATABASE_URL=sqlite:///data.db
  - flask db init
  - flask db migrate -m "Initial Migration"
script:
  - pytest --cov=Mess_Management_System tests/
notifications:
  on_success: always
  on_failure: always